services:
  mediamtx:
    image: livepeerci/mediamtx
    container_name: live-video-to-video-mediamtx
    volumes:
      - ./configs/mediamtx/mediamtx.yml:/mediamtx.yml
    ports:
      - "1935:1935"
      - "8890:8890"
      - "9997:9997"