services:

  ai-job-tester:
    image: tztcloud/ai-job-tester:2.0-5
    container_name: "ai-job-tester"
    restart: unless-stopped
    volumes:
      - ai-job-tester:/app/configs
    environment:
      - TZ=UTC
      - CRONTAB_SCHEDULE=0 */2 * * *
      - CONFIG_FILE=/app/configs/config-live-video-to-video-pipelines.json
    depends_on:
      - tester-gateway

  tester-gateway:
    image: tztcloud/go-livepeer:v0.8.9-NaaP-M1
    restart: unless-stopped
    hostname: ai-tester-gateway
    container_name: ai-tester-gateway
    environment:
      - LIVEPEER_OS_HTTP_TIMEOUT=8s
      - LIVEPEER_TESTER_GATEWAY_ENABLED=true
    volumes:
      - tester-gateway-lpData:/root/.lpData
    command: '-ethUrl=YOUR_RPC_URL
              -ethPassword=/root/.lpData/eth-secret.txt
              -ethKeystorePath=/root/.lpData
              -network=arbitrum-one-mainnet
              -serviceAddr=ai-tester-gateway:8935
              -cliAddr=ai-tester-gateway:7935
              -gateway=true
              -monitor=true
              -maxPricePerUnit=125000000
              -maxTotalEV=100000000000000
              -v=6
              -pixelsPerUnit=1
              -blockPollingInterval=20
              -httpIngest=true
              -httpAddr=0.0.0.0:8935
              -rtmpAddr=0.0.0.0:1936
              -orchMinLivepeerVersion=v0.8.6
              -discoveryTimeout=750ms
              '

volumes:
  tester-gateway-lpData:
    external: true
  ai-job-tester:
    external: true